### ISSUE TITLE
MariaDB version 10.0.27 build failing Ubuntu Trusty64

### ISSUE THREAD

**Issue by Liam-Power** [sous-chefs/mariadb#114]
There was a new release of MariaDB 5 days ago which seems to have broken the install process. I have updated from 0.2.12 to 0.3.1 to see if that fixed the issue and it still hasn't.

It also seems that you cannot specify a minor version of MariaDB to use, which would be useful in this case.

Here are the settings I am using:
 "mariadb" : {
      "use_default_repository": true,
      "server_root_password": "root",
      "mysqld": {
        "connect_timeout": 600,
        "wait_timeout": 1800,
        "open_files_limit": "24000"
      }
    },

Stack trace output below.

0.2.12
Generated at 2016-08-29 13:08:58 +0000
Mixlib::ShellOut::ShellCommandFailed: package[mariadb-server-10.0](mariadb::_debian_server line 53) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of apt-get -q -y install mariadb-server-10.0=10.0.27+maria-1~trusty ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  chef-zero erubis ohai ruby-diff-lcs ruby-erubis ruby-hashie ruby-highline
  ruby-ipaddress ruby-mime-types ruby-mixlib-authentication ruby-mixlib-cli
  ruby-mixlib-config ruby-mixlib-log ruby-mixlib-shellout ruby-net-ssh
  ruby-net-ssh-gateway ruby-net-ssh-multi ruby-rack ruby-rest-client
  ruby-sigar ruby-systemu ruby-yajl
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libaio1 libdbd-mysql-perl libdbi-perl libhtml-template-perl
  libmariadbclient18 libmysqlclient18 libreadline5 mariadb-client-10.0
  mariadb-client-core-10.0 mariadb-common mariadb-server-core-10.0
  mysql-common
Suggested packages:
  libclone-perl libmldbm-perl libnet-daemon-perl libplrpc-perl
  libsql-statement-perl libipc-sharedcache-perl libterm-readkey-perl mailx
  mariadb-test tinyca
The following NEW packages will be installed:
  libaio1 libdbd-mysql-perl libdbi-perl libhtml-template-perl
  libmariadbclient18 libmysqlclient18 libreadline5 mariadb-client-10.0
  mariadb-client-core-10.0 mariadb-common mariadb-server-10.0
  mariadb-server-core-10.0 mysql-common
0 upgraded, 13 newly installed, 0 to remove and 143 not upgraded.
Need to get 13.9 MB of archives.
After this operation, 137 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libaio1 amd64 0.3.109-4 [6,364 B]
Get:2 http://lon1.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu/ trusty/main mysql-common all 10.0.27+maria-1~trusty [8,328 B]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main libreadline5 amd64 5.2+dfsg-2 [130 kB]
Get:4 http://lon1.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu/ trusty/main mariadb-common all 10.0.27+maria-1~trusty [3,208 B]
Get:5 http://lon1.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu/ trusty/main libmariadbclient18 amd64 10.0.27+maria-1~trusty [566 kB]
Get:6 http://archive.ubuntu.com/ubuntu/ trusty/main libdbi-perl amd64 1.630-1 [879 kB]
Get:7 http://lon1.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu/ trusty/main libmysqlclient18 amd64 10.0.27+maria-1~trusty [2,882 B]
Get:8 http://lon1.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu/ trusty/main mariadb-client-core-10.0 amd64 10.0.27+maria-1~trusty [669 kB]
Get:9 http://archive.ubuntu.com/ubuntu/ trusty/main libdbd-mysql-perl amd64 4.025-1 [99.3 kB]
Get:10 http://archive.ubuntu.com/ubuntu/ trusty/main libhtml-template-perl all 2.95-1 [65.5 kB]
Get:11 http://lon1.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu/ trusty/main mariadb-client-10.0 amd64 10.0.27+maria-1~trusty [1,053 kB]
Get:12 http://lon1.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu/ trusty/main mariadb-server-core-10.0 amd64 10.0.27+maria-1~trusty [4,396 kB]
Get:13 http://lon1.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu/ trusty/main mariadb-server-10.0 amd64 10.0.27+maria-1~trusty [6,067 kB]
Preconfiguring packages ...
Fetched 13.9 MB in 2s (5,576 kB/s)
Selecting previously unselected package libaio1:amd64.
(Reading database ... 79894 files and directories currently installed.)
Preparing to unpack .../libaio1_0.3.109-4_amd64.deb ...
Unpacking libaio1:amd64 (0.3.109-4) ...
Selecting previously unselected package libreadline5:amd64.
Preparing to unpack .../libreadline5_5.2+dfsg-2_amd64.deb ...
Unpacking libreadline5:amd64 (5.2+dfsg-2) ...
Selecting previously unselected package mysql-common.
Preparing to unpack .../mysql-common_10.0.27+maria-1~trusty_all.deb ...
Unpacking mysql-common (10.0.27+maria-1~trusty) ...
Selecting previously unselected package mariadb-common.
Preparing to unpack .../mariadb-common_10.0.27+maria-1~trusty_all.deb ...
Unpacking mariadb-common (10.0.27+maria-1~trusty) ...
Selecting previously unselected package libdbi-perl.
Preparing to unpack .../libdbi-perl_1.630-1_amd64.deb ...
Unpacking libdbi-perl (1.630-1) ...
Selecting previously unselected package libmariadbclient18.
Preparing to unpack .../libmariadbclient18_10.0.27+maria-1~trusty_amd64.deb ...
Unpacking libmariadbclient18 (10.0.27+maria-1~trusty) ...
Selecting previously unselected package libmysqlclient18.
Preparing to unpack .../libmysqlclient18_10.0.27+maria-1~trusty_amd64.deb ...
Unpacking libmysqlclient18 (10.0.27+maria-1~trusty) ...
Selecting previously unselected package libdbd-mysql-perl.
Preparing to unpack .../libdbd-mysql-perl_4.025-1_amd64.deb ...
Unpacking libdbd-mysql-perl (4.025-1) ...
Selecting previously unselected package mariadb-client-core-10.0.
Preparing to unpack .../mariadb-client-core-10.0_10.0.27+maria-1~trusty_amd64.deb ...
Unpacking mariadb-client-core-10.0 (10.0.27+maria-1~trusty) ...
Selecting previously unselected package mariadb-client-10.0.
Preparing to unpack .../mariadb-client-10.0_10.0.27+maria-1~trusty_amd64.deb ...
Unpacking mariadb-client-10.0 (10.0.27+maria-1~trusty) ...
Selecting previously unselected package mariadb-server-core-10.0.
Preparing to unpack .../mariadb-server-core-10.0_10.0.27+maria-1~trusty_amd64.deb ...
Unpacking mariadb-server-core-10.0 (10.0.27+maria-1~trusty) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up mysql-common (10.0.27+maria-1~trusty) ...
Setting up mariadb-common (10.0.27+maria-1~trusty) ...
Selecting previously unselected package mariadb-server-10.0.
(Reading database ... 80253 files and directories currently installed.)
Preparing to unpack .../mariadb-server-10.0_10.0.27+maria-1~trusty_amd64.deb ...
Selecting previously unselected package libhtml-template-perl.
Preparing to unpack .../libhtml-template-perl_2.95-1_all.deb ...
Unpacking libhtml-template-perl (2.95-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
STDERR: Aborting downgrade from (at least) 10.1 to 10.0.
If are sure you want to downgrade to 10.0, remove the file
/var/lib/mysql/debian-*.flag and try installing again.
dpkg: error processing archive /var/cache/apt/archives/mariadb-server-10.0_10.0.27+maria-1~trusty_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/mariadb-server-10.0_10.0.27+maria-1~trusty_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
---- End output of apt-get -q -y install mariadb-server-10.0=10.0.27+maria-1~trusty ----
Ran apt-get -q -y install mariadb-server-10.0=10.0.27+maria-1~trusty returned 100
/var/lib/gems/2.2.0/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:272:in `invalid!'
/var/lib/gems/2.2.0/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:259:in`error!'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/mixin/shell_out.rb:43:in `shell_out!'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/provider/package/apt.rb:126:in`run_noninteractive'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/provider/package/apt.rb:94:in `install_package'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/provider/package.rb:82:in`block in action_install'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/mixin/why_run.rb:52:in `call'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/mixin/why_run.rb:52:in`add_action'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/provider.rb:155:in `converge_by'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/provider/package.rb:80:in`action_install'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/provider.rb:120:in `run_action'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource.rb:637:in`run_action'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/runner.rb:49:in `run_action'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/runner.rb:81:in`block (2 levels) in converge'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/runner.rb:81:in `each'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/runner.rb:81:in`block in converge'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:116:in`call'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:85:in`step'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:55:in`each_with_index'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection.rb:96:in `execute_each_resource'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/runner.rb:80:in`converge'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/client.rb:345:in `converge'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/client.rb:431:in`do_run'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/client.rb:213:in `block in run'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/client.rb:207:in`fork'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/client.rb:207:in `run'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/application.rb:217:in`run_chef_client'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/application/solo.rb:221:in `block in run_application'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/application/solo.rb:213:in`loop'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/application/solo.rb:213:in `run_application'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/application.rb:67:in`run'
/var/lib/gems/2.2.0/gems/chef-11.12.4/bin/chef-solo:25:in `<top (required)>'
/usr/local/bin/chef-solo:23:in`load'
/usr/local/bin/chef-solo:23:in `<main>'

0.3.1

Generated at 2016-08-29 12:53:08 +0000
Mixlib::ShellOut::ShellCommandFailed: package[mariadb-server-10.0](mariadb::_debian_server line 53) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of apt-get -q -y install mariadb-server-10.0=10.0.27+maria-1~trusty ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  chef-zero erubis ohai ruby-diff-lcs ruby-erubis ruby-hashie ruby-highline
  ruby-ipaddress ruby-mime-types ruby-mixlib-authentication ruby-mixlib-cli
  ruby-mixlib-config ruby-mixlib-log ruby-mixlib-shellout ruby-net-ssh
  ruby-net-ssh-gateway ruby-net-ssh-multi ruby-rack ruby-rest-client
  ruby-sigar ruby-systemu ruby-yajl
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libaio1 libdbd-mysql-perl libdbi-perl libhtml-template-perl
  libmariadbclient18 libmysqlclient18 libreadline5 mariadb-client-10.0
  mariadb-client-core-10.0 mariadb-common mariadb-server-core-10.0
  mysql-common
Suggested packages:
  libclone-perl libmldbm-perl libnet-daemon-perl libplrpc-perl
  libsql-statement-perl libipc-sharedcache-perl libterm-readkey-perl mailx
  mariadb-test tinyca
The following NEW packages will be installed:
  libaio1 libdbd-mysql-perl libdbi-perl libhtml-template-perl
  libmariadbclient18 libmysqlclient18 libreadline5 mariadb-client-10.0
  mariadb-client-core-10.0 mariadb-common mariadb-server-10.0
  mariadb-server-core-10.0 mysql-common
0 upgraded, 13 newly installed, 0 to remove and 143 not upgraded.
Need to get 13.9 MB of archives.
After this operation, 137 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libaio1 amd64 0.3.109-4 [6,364 B]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty/main libreadline5 amd64 5.2+dfsg-2 [130 kB]
Get:3 http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu/ trusty/main mysql-common all 10.0.27+maria-1~trusty [8,328 B]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main libdbi-perl amd64 1.630-1 [879 kB]
Get:5 http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu/ trusty/main mariadb-common all 10.0.27+maria-1~trusty [3,208 B]
Get:6 http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu/ trusty/main libmariadbclient18 amd64 10.0.27+maria-1~trusty [566 kB]
Get:7 http://archive.ubuntu.com/ubuntu/ trusty/main libdbd-mysql-perl amd64 4.025-1 [99.3 kB]
Get:8 http://archive.ubuntu.com/ubuntu/ trusty/main libhtml-template-perl all 2.95-1 [65.5 kB]
Get:9 http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu/ trusty/main libmysqlclient18 amd64 10.0.27+maria-1~trusty [2,882 B]
Get:10 http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu/ trusty/main mariadb-client-core-10.0 amd64 10.0.27+maria-1~trusty [669 kB]
Get:11 http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu/ trusty/main mariadb-client-10.0 amd64 10.0.27+maria-1~trusty [1,053 kB]
Get:12 http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu/ trusty/main mariadb-server-core-10.0 amd64 10.0.27+maria-1~trusty [4,396 kB]
Get:13 http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu/ trusty/main mariadb-server-10.0 amd64 10.0.27+maria-1~trusty [6,067 kB]
Preconfiguring packages ...
Fetched 13.9 MB in 2s (5,411 kB/s)
Selecting previously unselected package libaio1:amd64.
(Reading database ... 79894 files and directories currently installed.)
Preparing to unpack .../libaio1_0.3.109-4_amd64.deb ...
Unpacking libaio1:amd64 (0.3.109-4) ...
Selecting previously unselected package libreadline5:amd64.
Preparing to unpack .../libreadline5_5.2+dfsg-2_amd64.deb ...
Unpacking libreadline5:amd64 (5.2+dfsg-2) ...
Selecting previously unselected package mysql-common.
Preparing to unpack .../mysql-common_10.0.27+maria-1~trusty_all.deb ...
Unpacking mysql-common (10.0.27+maria-1~trusty) ...
Selecting previously unselected package mariadb-common.
Preparing to unpack .../mariadb-common_10.0.27+maria-1~trusty_all.deb ...
Unpacking mariadb-common (10.0.27+maria-1~trusty) ...
Selecting previously unselected package libdbi-perl.
Preparing to unpack .../libdbi-perl_1.630-1_amd64.deb ...
Unpacking libdbi-perl (1.630-1) ...
Selecting previously unselected package libmariadbclient18.
Preparing to unpack .../libmariadbclient18_10.0.27+maria-1~trusty_amd64.deb ...
Unpacking libmariadbclient18 (10.0.27+maria-1~trusty) ...
Selecting previously unselected package libmysqlclient18.
Preparing to unpack .../libmysqlclient18_10.0.27+maria-1~trusty_amd64.deb ...
Unpacking libmysqlclient18 (10.0.27+maria-1~trusty) ...
Selecting previously unselected package libdbd-mysql-perl.
Preparing to unpack .../libdbd-mysql-perl_4.025-1_amd64.deb ...
Unpacking libdbd-mysql-perl (4.025-1) ...
Selecting previously unselected package mariadb-client-core-10.0.
Preparing to unpack .../mariadb-client-core-10.0_10.0.27+maria-1~trusty_amd64.deb ...
Unpacking mariadb-client-core-10.0 (10.0.27+maria-1~trusty) ...
Selecting previously unselected package mariadb-client-10.0.
Preparing to unpack .../mariadb-client-10.0_10.0.27+maria-1~trusty_amd64.deb ...
Unpacking mariadb-client-10.0 (10.0.27+maria-1~trusty) ...
Selecting previously unselected package mariadb-server-core-10.0.
Preparing to unpack .../mariadb-server-core-10.0_10.0.27+maria-1~trusty_amd64.deb ...
Unpacking mariadb-server-core-10.0 (10.0.27+maria-1~trusty) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up mysql-common (10.0.27+maria-1~trusty) ...
Setting up mariadb-common (10.0.27+maria-1~trusty) ...
Selecting previously unselected package mariadb-server-10.0.
(Reading database ... 80253 files and directories currently installed.)
Preparing to unpack .../mariadb-server-10.0_10.0.27+maria-1~trusty_amd64.deb ...
Selecting previously unselected package libhtml-template-perl.
Preparing to unpack .../libhtml-template-perl_2.95-1_all.deb ...
Unpacking libhtml-template-perl (2.95-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
STDERR: Aborting downgrade from (at least) 10.1 to 10.0.
If are sure you want to downgrade to 10.0, remove the file
/var/lib/mysql/debian-*.flag and try installing again.
dpkg: error processing archive /var/cache/apt/archives/mariadb-server-10.0_10.0.27+maria-1~trusty_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/mariadb-server-10.0_10.0.27+maria-1~trusty_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
---- End output of apt-get -q -y install mariadb-server-10.0=10.0.27+maria-1~trusty ----
Ran apt-get -q -y install mariadb-server-10.0=10.0.27+maria-1~trusty returned 100
/var/lib/gems/2.2.0/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:272:in `invalid!'
/var/lib/gems/2.2.0/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:259:in`error!'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/mixin/shell_out.rb:43:in `shell_out!'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/provider/package/apt.rb:126:in`run_noninteractive'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/provider/package/apt.rb:94:in `install_package'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/provider/package.rb:82:in`block in action_install'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/mixin/why_run.rb:52:in `call'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/mixin/why_run.rb:52:in`add_action'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/provider.rb:155:in `converge_by'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/provider/package.rb:80:in`action_install'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/provider.rb:120:in `run_action'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource.rb:637:in`run_action'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/runner.rb:49:in `run_action'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/runner.rb:81:in`block (2 levels) in converge'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/runner.rb:81:in `each'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/runner.rb:81:in`block in converge'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:116:in`call'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:85:in`step'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:55:in`each_with_index'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/resource_collection.rb:96:in `execute_each_resource'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/runner.rb:80:in`converge'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/client.rb:345:in `converge'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/client.rb:431:in`do_run'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/client.rb:213:in `block in run'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/client.rb:207:in`fork'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/client.rb:207:in `run'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/application.rb:217:in`run_chef_client'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/application/solo.rb:221:in `block in run_application'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/application/solo.rb:213:in`loop'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/application/solo.rb:213:in `run_application'
/var/lib/gems/2.2.0/gems/chef-11.12.4/lib/chef/application.rb:67:in`run'
/var/lib/gems/2.2.0/gems/chef-11.12.4/bin/chef-solo:25:in `<top (required)>'
/usr/local/bin/chef-solo:23:in`load'

**Comment by Liam-Power** [comment]
I'm closing this as it appears to work fine now. I'm guessing it was to do with the MariaDB's repo.
