### ISSUE TITLE
Server configuration not loaded immediately

### ISSUE THREAD

**Issue by belsander** [sous-chefs/mariadb#163]
When using both the resources `mariadb_configuration` and `mariadb_replication` I noticed that the `mariadb_configuration` modifies the proper configuration files, but mariadb does not get reloaded to load the new configuration.

This is an issue since I you need to set the 'server_id' for replication to work.

The relevant resources:
```
mariadb_configuration 'replication-slave' do
  section 'mysqld'
  option 'server_id' => 2, 
    'gtid_domain_id' => 2
end
```
```
%w(add start).each do |repl_action|
  mariadb_replication 'default' do
    sensitive true
    master_host '127.0.0.2'
    master_user 'replication_user'
    master_password 'replication_password'
    master_use_gtid 'slave_pos'
    action repl_action
  end
end
```

The output of Kitchen test:
```
       Recipe: mariadb::server
         * service[mysql] action nothing (skipped due to action :nothing)
       Recipe: mariadb::repository
         * apt_repository[mariadb-10.0] action add
           * execute[install-key F1656F24C74CD1D8] action run
             - execute apt-key adv --recv --keyserver hkp://keyserver.ubuntu.com:80 F1656F24C74CD1D8
           * execute[apt-cache gencaches] action run
             - execute apt-cache gencaches
           * execute[apt-cache gencaches] action nothing (skipped due to action :nothing)
           * apt_update[mariadb-10.0] action nothing (skipped due to action :nothing)
           * file[/etc/apt/sources.list.d/mariadb-10.0.list] action create
             - create new file /etc/apt/sources.list.d/mariadb-10.0.list
             - update content in file /etc/apt/sources.list.d/mariadb-10.0.list from none to 30fa24
             --- /etc/apt/sources.list.d/mariadb-10.0.list	2017-05-23 16:05:41.719317355 +0000
             +++ /etc/apt/sources.list.d/.chef-mariadb-1020170523-1946-oxnqr2.0.list	2017-05-23 16:05:41.719317355 +0000
             @@ -1 +1,2 @@
             +deb      "http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu" xenial main
             - change mode from '' to '0644'
             - change owner from '' to 'root'
             - change group from '' to 'root'
           * execute[apt-cache gencaches] action run
             - execute apt-cache gencaches
           * apt_update[mariadb-10.0] action update
             - force update new lists of packages
             * directory[/var/lib/apt/periodic] action create (up to date)
             * directory[/etc/apt/apt.conf.d] action create (up to date)
             * file[/etc/apt/apt.conf.d/15update-stamp] action create_if_missing (up to date)
             * execute[apt-get -q update] action run
        - execute apt-get -q update
       Recipe: mariadb::_debian_server
         * apt_package[debconf-utils] action install
           - install version 1.5.58ubuntu1 of package debconf-utils
         * template[/var/cache/local/preseeding/mariadb-server.seed] action create
           - create new file /var/cache/local/preseeding/mariadb-server.seed
           - update content in file /var/cache/local/preseeding/mariadb-server.seed from none to 7cc0c5
           - suppressed sensitive resource
           - change mode from '' to '0600'
           - change owner from '' to 'root'
           - change group from '' to 'root'
         * execute[preseed mariadb-server] action run
           - execute /usr/bin/debconf-set-selections /var/cache/local/preseeding/mariadb-server.seed
         * execute[preseed mariadb-server] action nothing (skipped due to action :nothing)
       Recipe: mariadb::server
         * apt_package[MariaDB-server] action install
           - install version 10.0.31+maria-1~xenial of package mariadb-server-10.0
       Recipe: mariadb::config
         * template[/root/.my.cnf] action create (skipped due to only_if)
         * template[/etc/mysql/my.cnf] action create
           - update content in file /etc/mysql/my.cnf from fa1a1c to 4fcf91
           --- /etc/mysql/my.cnf	2017-05-19 23:20:44.000000000 +0000
           +++ /etc/mysql/.chef-my20170523-1946-65fr7l.cnf	2017-05-23 16:06:30.387637592 +0000
           @@ -1,9 +1,10 @@
           +# DEPLOYED BY CHEF
            # MariaDB database server configuration file.
            #
            # You can copy this file to one of:
            # - "/etc/mysql/my.cnf" to set global options,
            # - "~/.my.cnf" to set user-specific options.
           -# 
           +#
            # One can use all long options that the program supports.
            # Run program with --help to get a list of available options and with
            # --print-defaults to see which it would actually understand and use.
           @@ -37,7 +38,7 @@
            port		= 3306
            basedir		= /usr
            datadir		= /var/lib/mysql
           -tmpdir		= /tmp
           +tmpdir		= /var/tmp
            lc_messages_dir	= /usr/share/mysql
            lc_messages	= en_US
            skip-external-locking
           @@ -64,7 +65,6 @@
            # the first time they are touched. On error, make copy and try a repair.
            myisam_recover          = BACKUP
            key_buffer_size		= 128M
           -#open-files-limit	= 2000
            table_open_cache	= 400
            myisam_sort_buffer_size	= 512M
            concurrent_insert	= 2
           @@ -84,8 +84,8 @@
            # Both location gets rotated by the cronjob.
            # Be aware that this log type is a performance killer.
            # As of 5.1 you can enable the log at runtime!
           -#general_log_file        = /var/log/mysql/mysql.log
           -#general_log             = 1
           +general_log_file        = /var/log/mysql/mysql.log
           +general_log             = 0
            #
            # Error logging goes to syslog due to /etc/mysql/conf.d/mysqld_safe_syslog.cnf.
            #
           @@ -94,10 +94,13 @@
            #
            # Enable the slow query log to see queries with especially long duration
            #slow_query_log[={0|1}]
           +slow_query_log = 0
            slow_query_log_file	= /var/log/mysql/mariadb-slow.log
            long_query_time = 10
           -#log_slow_rate_limit	= 1000
           +log_slow_rate_limit	= 1000
            log_slow_verbosity	= query_plan
           +# Logging output type
           +log_output = FILE
            
            #log-queries-not-using-indexes
            #log_slow_admin_statements
           @@ -105,16 +108,11 @@
            # The following can be used as easy to replay backup logs or for replication.
            # note: if you are setting up a replication slave, see README.Debian about
            #       other settings you may need to change.
           -#server-id		= 1
            #report_host		= master1
            #auto_increment_increment = 2
            #auto_increment_offset	= 1
           -log_bin			= /var/log/mysql/mariadb-bin
           -log_bin_index		= /var/log/mysql/mariadb-bin.index
            # not fab for performance, but safer
            #sync_binlog		= 1
           -expire_logs_days	= 10
           -max_binlog_size         = 100M
            # slaves
            #relay_log		= /var/log/mysql/relay-bin
            #relay_log_index	= /var/log/mysql/relay-bin.index
           @@ -125,20 +123,9 @@
            # If applications support it, this stricter sql_mode prevents some
            # mistakes like inserting invalid dates etc.
            #sql_mode		= NO_ENGINE_SUBSTITUTION,TRADITIONAL
           -#
           -# * InnoDB
           -#
           -# InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.
           -# Read the manual for more InnoDB related options. There are many!
           +
            default_storage_engine	= InnoDB
           -# you can't just change log file size, requires special procedure
           -#innodb_log_file_size	= 50M
           -innodb_buffer_pool_size	= 256M
           -innodb_log_buffer_size	= 8M
           -innodb_file_per_table	= 1
           -innodb_open_files	= 400
           -innodb_io_capacity	= 400
           -innodb_flush_method	= O_DIRECT
           +
            #
            # * Security Features
            #
           @@ -152,10 +139,11 @@
            # ssl-key=/etc/mysql/server-key.pem
            
            
           +#
           +# * Plugins Options
           +#
            
            [mysqldump]
           -quick
           -quote-names
            max_allowed_packet	= 16M
            
            [mysql]
         * directory[/etc/my.cnf.d/] action create
           - create new directory /etc/my.cnf.d/
           - change mode from '' to '0755'
           - change owner from '' to 'root'
           - change group from '' to 'root'
         * mariadb_configuration[20-innodb] action add
           * template[/etc/mysql/conf.d/20-innodb.cnf] action create
             - create new file /etc/mysql/conf.d/20-innodb.cnf
             - update content in file /etc/mysql/conf.d/20-innodb.cnf from none to 36e5ec
             - suppressed sensitive resource
             - change mode from '' to '0640'
             - change owner from '' to 'root'
             - change group from '' to 'mysql'
         
         * mariadb_configuration[30-replication] action add
           * template[/etc/mysql/conf.d/30-replication.cnf] action create
             - create new file /etc/mysql/conf.d/30-replication.cnf
             - update content in file /etc/mysql/conf.d/30-replication.cnf from none to b2d844
             - suppressed sensitive resource
             - change mode from '' to '0640'
             - change owner from '' to 'root'
             - change group from '' to 'mysql'
         
       Recipe: mariadb::server
         * execute[mariadb-service-restart-needed] action run (skipped due to only_if)
         * execute[install-grants] action nothing (skipped due to action :nothing)
         * template[/etc/mariadb_grants] action create
           - create new file /etc/mariadb_grants
           - update content in file /etc/mariadb_grants from none to b48b52
           - suppressed sensitive resource
           - change mode from '' to '0600'
           - change owner from '' to 'root'
           - change group from '' to 'root'
         * execute[install-grants] action run
           - execute sensitive resource
       Recipe: slave-database::default
         * mariadb_configuration[replication-slave] action add
           * template[/etc/mysql/conf.d/replication-slave.cnf] action create
             - create new file /etc/mysql/conf.d/replication-slave.cnf
             - update content in file /etc/mysql/conf.d/replication-slave.cnf from none to ca5c89
             - suppressed sensitive resource
             - change mode from '' to '0640'
             - change owner from '' to 'root'
             - change group from '' to 'mysql'
         
       Recipe: chef-vault::default
         * chef_gem[chef-vault] action install (up to date)
       Recipe: slave-database::users
         * log[info attributes] action write
         
         * ruby_block[check if MySQL root password is needed] action create
           - execute the ruby block check if MySQL root password is needed
         * bash[setup root user] action run
           - execute sensitive resource
         * bash[setup root user] action nothing (skipped due to action :nothing)
       Recipe: slave-database::replication
         * mariadb_replication[default] action add
           * mysql2_gem[mysql2] action install
           Recipe: mariadb::devel
             * apt_package[MariaDB-devel] action install
        - install version 10.0.31+maria-1~xenial of package libmariadbclient-dev
             * build_essential[install_packages] action install
        * apt_package[autoconf, binutils-doc, bison, build-essential, flex, gettext, ncurses-dev] action install
          - install version 2.69-9 of package autoconf
          - install version 2.26.1-1ubuntu1~16.04.3 of package binutils-doc
          - install version 2:3.0.4.dfsg-1 of package bison
          - install version 12.1ubuntu2 of package build-essential
          - install version 2.6.0-11 of package flex
          - install version 0.19.7-2ubuntu3 of package gettext
          - install version 6.0+20160213-1ubuntu1 of package ncurses-dev
             
             * gem_package[mysql2] action install
        - install version 0.4.6 of package mysql2
           
           - create default
           -   set master_host     to (suppressed sensitive property)
           -   set master_port     to (suppressed sensitive property) (default value)
           -   set master_user     to (suppressed sensitive property)
           -   set master_password to (suppressed sensitive property)
           -   set master_use_gtid to (suppressed sensitive property)
         * mysql2_gem[mysql2] action install
           * build_essential[install_packages] action install
             * apt_package[autoconf, binutils-doc, bison, build-essential, flex, gettext, ncurses-dev] action install (up to date)
       (up to date)
           * gem_package[mysql2] action install (up to date)
            (up to date)
       Recipe: slave-database::replication
         * mariadb_replication[default] action start
           * mysql2_gem[mysql2] action install
             * build_essential[install_packages] action install
        * apt_package[autoconf, binutils-doc, bison, build-essential, flex, gettext, ncurses-dev] action install (up to date)
         (up to date)
             * gem_package[mysql2] action install (up to date)
       (up to date)
           
           ================================================================================
           Error executing action `start` on resource 'mariadb_replication[default]'
           ================================================================================
           
           RuntimeError
           ------------
           Mysql query error: Misconfigured slave: server_id was not set; Fix in config file
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/mariadb/libraries/mariadb_conn_helper.rb:49:in `rescue in query'
           /tmp/kitchen/cache/cookbooks/mariadb/libraries/mariadb_conn_helper.rb:45:in `query'
           /tmp/kitchen/cache/cookbooks/mariadb/resources/replication.rb:37:in `replication_query'
           /tmp/kitchen/cache/cookbooks/mariadb/resources/replication.rb:90:in `start_slave'
           /tmp/kitchen/cache/cookbooks/mariadb/resources/replication.rb:187:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           suppressed sensitive resource output
           
           Compiled Resource:
           ------------------
           suppressed sensitive resource output
           
           System Info:
           ------------
           chef_version=13.0.118
           platform=ubuntu
           platform_version=16.04
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
           program_name=chef-client worker: ppid=1940;start=16:05:22;
           executable=/opt/chef/bin/chef-client
           
       Recipe: mariadb::server
         * service[mysql] action enable (up to date)
       
       Running handlers:
       [2017-05-23T16:18:51+00:00] ERROR: Running exception handlers
       [2017-05-23T16:18:51+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-05-23T16:18:51+00:00] ERROR: Exception handlers complete
       [2017-05-23T16:18:51+00:00] ERROR: Exception handlers complete
       Chef Client failed. 47 resources updated in 13 minutes 28 seconds
       [2017-05-23T16:18:51+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-05-23T16:18:51+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-05-23T16:18:51+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-05-23T16:18:51+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-05-23T16:18:51+00:00] ERROR: mariadb_replication[default] (slave-database::replication line 9) had an error: RuntimeError: Mysql query error: Misconfigured slave: server_id was not set; Fix in config file
       [2017-05-23T16:18:51+00:00] ERROR: mariadb_replication[default] (slave-database::replication line 9) had an error: RuntimeError: Mysql query error: Misconfigured slave: server_id was not set; Fix in config file
       [2017-05-23T16:18:51+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
       [2017-05-23T16:18:51+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by shoekstra** [comment]
Hi @belsander !

First, is it possible to provide an example kitchen suite I can use to reproduce?  We have a TK test for replication that passes and curious to see why yours fails and to fix ours if it is a false positive.

Second re the service not restarting when config is updated, this seems to be by design.  It was implemented before I started with this cookbook and I assume the reason is you wouldn't want multiple nodes in a cluster to restart at the same time as it would result in a stopped cluster. I presume the author wanted people to run Chef and restart the mysql service in a more managed way than a Chef run.  I would like to add an attribute that will allow Chef to reload the service if the config changes; it would default to disabled but would fix your use case.

If you could help me reproduce the failing TK suites I can look further into the issue.

Cheers,
Stephen

**Comment by belsander** [comment]
Sure thing, thanks for helping out!

```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[slave-database::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
```
I understand the issue with stopping the cluster, but a simple reload of the configuration would suffice here, I assume? Another way would be to set the configuration settings on the fly by using SQL statements.

Let me know how the tests turn out

**Comment by shoekstra** [comment]
Thanks - is there any more than those two resources you mentioned in original post?

Work has been a bit busy last few days but hope to get on this one when I have a gap.  Sorry for the delay!

**Comment by belsander** [comment]
No worries, I'll see this afternoon if I can get the other resources up here on Github.
