### ISSUE TITLE
mariadb_replication provider, generate compilation error

### ISSUE THREAD

**Issue by sinfomicien** [sous-chefs/mariadb#18]
When we test it from another cookbook (test using chefspec):

```
================================================================================
Recipe Compile Error in /tmp/d20141006-20941-1gwi9sq/cookbooks/r_dbslave/recipes/default.rb
================================================================================

TypeError
---------
class or module required

Cookbook Trace:
---------------
  /tmp/d20141006-20941-1gwi9sq/cookbooks/r_dbslave/recipes/default.rb:157:in `block (2 levels) in from_file'
  /tmp/d20141006-20941-1gwi9sq/cookbooks/r_dbslave/recipes/default.rb:155:in `block in from_file'
  /tmp/d20141006-20941-1gwi9sq/cookbooks/r_dbslave/recipes/default.rb:154:in `each'
  /tmp/d20141006-20941-1gwi9sq/cookbooks/r_dbslave/recipes/default.rb:154:in `from_file'

Relevant File Content:
----------------------
/tmp/d20141006-20941-1gwi9sq/cookbooks/r_dbslave/recipes/default.rb:

150:          node['r_dbslave']['master']['galera_cluster_name']
151:      )
152:  
153:      # Setup all values to have a working slave setup
154:      galera_cluster_nodes.each do |node_master|
155:        mariadb_replication node_master.name do
156:          action [:add, :start]
157>>         master_user 'user'
158:          master_password 'password'
159:          master_host node_master.ipaddress
160:          master_use_gtid 'current_pos'
161:        end
162:      end
163:    end
164:  end
165:
```

**Comment by sinfomicien** [comment]
Ok, yes, it was just nil instead of NilClass. good correction.
