### ISSUE TITLE
Managing service[mysql] on CentOS bug

### ISSUE THREAD

**Issue by ghost** [sous-chefs/mariadb#207]
Hello have faced with issue on installing mariadb server 10.2 on Centos 6.9 final release and 7.0 aswell, looks like chef unable to manage just created mysql service, maybe its problem  of chef itself I dnt know. Here posts the output log, do you have any ideas:
```
localhost Recipe: mariadb::server
localhost   * directory[/var/log/mysql] action create (up to date)
localhost   * execute[mariadb-service-restart-needed] action run
localhost     - execute true
localhost   * ruby_block[restart_mysql] action run
localhost     - execute the ruby block restart_mysql
localhost   * service[mysql] action enable
localhost     * service[mysql]: Service is not known to chkconfig.
localhost     ================================================================================
localhost     Error executing action `enable` on resource 'service[mysql]'
localhost     ================================================================================
localhost
localhost     Chef::Exceptions::Service
localhost     -------------------------
localhost     service[mysql]: Service is not known to chkconfig.
localhost
localhost     Resource Declaration:
localhost     ---------------------
localhost     # In /var/chef/cache/cookbooks/mariadb/recipes/server.rb
localhost
localhost     129: service 'mysql' do
localhost     130:   service_name node['mariadb']['mysqld']['service_name']
localhost     131:   supports restart: true, reload: true
localhost     132:   action [:start, :enable]
localhost     133: end
localhost     134:
localhost
localhost     Compiled Resource:
localhost     ------------------
localhost     # Declared in /var/chef/cache/cookbooks/mariadb/recipes/server.rb:129:in `from_file'
localhost
localhost     service("mysql") do
localhost       action [:enable, :restart]
localhost       default_guard_interpreter :default
localhost       service_name "mariadb"
localhost       enabled nil
localhost       running nil
localhost       masked nil
localhost       pattern "mysql"
localhost       declared_type :service
localhost       cookbook_name "mariadb"
localhost       recipe_name "server"
localhost       supports {:restart=>true, :reload=>true}
localhost     end
localhost
localhost     System Info:
localhost     ------------
localhost     chef_version=14.1.12
localhost     platform=centos
localhost     platform_version=6.9
localhost     ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
localhost     program_name=/usr/bin/chef-client
localhost     executable=/opt/chef/bin/chef-client
localhost
localhost
localhost Running handlers:
localhost [2018-06-05T05:19:07-04:00] ERROR: Running exception handlers
localhost Running handlers complete
localhost [2018-06-05T05:19:07-04:00] ERROR: Exception handlers complete
localhost Chef Client failed. 7 resources updated in 01 minutes 27 seconds
localhost [2018-06-05T05:19:08-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
localhost [2018-06-05T05:19:08-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
localhost [2018-06-05T05:19:08-04:00] FATAL: Chef::Exceptions::Service: service[mysql] (mariadb::server line 129) had an error: Chef::Exceptions::Service: service[mysql]: Service is not known to chkconfig.
```
Observed on:
chef client versions:
- 12.1
- 14.1.12

centos platforms:
- CentOS release 6.9 (Final)
- CentOS release 7.0

cookbook versions:
- 1.5.2
- 1.5.3
- 1.5.4

[chef-stacktract.log](https://github.com/sous-chefs/mariadb/files/2071726/chef-stacktract.log)

**Comment by ghost** [comment]
I tried to comment the ```:enable``` option and I got the second error:
```
localhost Recipe: mariadb::server
localhost   * directory[/var/log/mysql] action create (up to date)
localhost   * execute[mariadb-service-restart-needed] action run
localhost     - execute true
localhost   * ruby_block[restart_mysql] action run
localhost     - execute the ruby block restart_mysql
localhost   * service[mysql] action restart
localhost     * service[mysql]: No custom command for restart specified and unable to locate the init.d script!
localhost     ================================================================================
localhost     Error executing action `restart` on resource 'service[mysql]'
localhost     ================================================================================
localhost
localhost     Chef::Exceptions::Service
localhost     -------------------------
localhost     service[mysql]: No custom command for restart specified and unable to locate the init.d script!
localhost
localhost     Resource Declaration:
localhost     ---------------------
localhost     # In /var/chef/cache/cookbooks/mariadb/recipes/server.rb
localhost
localhost     129: service 'mysql' do
localhost     130:   service_name node['mariadb']['mysqld']['service_name']
localhost     131:   supports restart: true, reload: true
localhost     132: #  action [:start, :enable]
localhost     133:   action [:start]
localhost     134: end
localhost     135:
localhost
localhost     Compiled Resource:
localhost     ------------------
localhost     # Declared in /var/chef/cache/cookbooks/mariadb/recipes/server.rb:129:in `from_file'
localhost
localhost     service("mysql") do
localhost       action [:restart]
localhost       default_guard_interpreter :default
localhost       service_name "mariadb"
localhost       enabled nil
localhost       running nil
localhost       masked nil
localhost       pattern "mysql"
localhost       declared_type :service
localhost       cookbook_name "mariadb"
localhost       recipe_name "server"
localhost       supports {:restart=>true, :reload=>true}
localhost     end
localhost
localhost     System Info:
localhost     ------------
localhost     chef_version=14.1.12
localhost     platform=centos
localhost     platform_version=6.9
localhost     ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
localhost     program_name=/usr/bin/chef-client
localhost     executable=/opt/chef/bin/chef-client
localhost
localhost
localhost Running handlers:
localhost [2018-06-05T05:33:27-04:00] ERROR: Running exception handlers
localhost Running handlers complete
localhost [2018-06-05T05:33:27-04:00] ERROR: Exception handlers complete
localhost Chef Client failed. 4 resources updated in 13 seconds
localhost [2018-06-05T05:33:27-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
localhost [2018-06-05T05:33:27-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
localhost [2018-06-05T05:33:27-04:00] FATAL: Chef::Exceptions::Service: service[mysql] (mariadb::server line 129) had an error: Chef::Exceptions::Service: service[mysql]: No custom command for restart specified and unable to locate the init.d script!
```
[chef-stacktrace.log](https://github.com/sous-chefs/mariadb/files/2071753/chef-stacktrace.log)

**Comment by ghost** [comment]
BTW, I tried to overwrite service_name attribute with "mysql"

```
default['mariadb']['mysqld']['service_name'] = 'mysql'
```
and errors disappear, but mariadb service not installing at all (missing daemon at /etc/init.d/)

**Comment by damacus** [comment]
hey @maxim-agrigoroae thanks for taking the time to submit this issue.

Right now we're lacking some maintainers. 

We want to look at fixing this up after we've cleaned up the postgresql cookbook to a good standard. Being a user of this cookbook we'd really appreciate some PRs for this. We'll happily help on the chef slack to debug and fix this issue if that helps! 

Welcome!

**Comment by ghost** [comment]
@damacus Sure, no problem, thank you very much )
